global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "unet-onnx"
    static_configs:
      - targets: ["host.docker.internal:8001"]

  - job_name: "prometheus"
    static_configs:
      - targets: ["prometheus:9090"]