global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "resnet-onnx"
    static_configs:
      - targets: ["resnet-onnx:8001"]

  - job_name: "prometheus"
    static_configs:
      - targets: ["prometheus:9090"]