apiVersion: apps/v1
kind: Deployment
metadata:
  name: flamenco-api
  labels:
    app: flamenco-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flamenco-api
  template:
    metadata:
      labels:
        app: flamenco-api
    spec:
      containers:
        - name: flamenco-api
          image: svane222/flamenco-api:latest
          imagePullPolicy: Always
          env:
            - name: ENVIRONMENT
              value: "PROD"
          ports:
            - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: flamenco-api-service
spec:
  selector:
    app: flamenco-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: flamenco-api-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: blender.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: flamenco-api-service
                port:
                  number: 80