apiVersion: apps/v1
kind: Deployment
metadata:
  name: resnet-onnx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: resnet-onnx
  template:
    metadata:
      labels:
        app: resnet-onnx
    spec:
      containers:
        - name: resnet-onnx
          image: svane222/resnet-onnx:cpu
          env:
            - name: PROMETHEUS_METRICS_ENABLED
              value: "true"
            - name: MAX_BATCH_SIZE
              value: "8"
            - name: USE_GPU
              value: "false"
          ports:
            - containerPort: 8001
---
apiVersion: v1
kind: Service
metadata:
  name: resnet-onnx
spec:
  type: ClusterIP
  selector:
    app: resnet-onnx
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 8001
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: resnet-onnx-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
spec:
  rules:
    - host: resnet-onnx
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: resnet-onnx
                port:
                  number: 8001