apiVersion: apps/v1
kind: Deployment
metadata:
  name: resnet-pytorch
spec:
  replicas: 1
  selector:
    matchLabels:
      app: resnet-pytorch
  template:
    metadata:
      labels:
        app: resnet-pytorch
    spec:
      containers:
        - name: resnet-pytorch
          image: svane222/resnet-pytorch:cpu
          env:
            - name: PROMETHEUS_METRICS_ENABLED
              value: "true"
            - name: MAX_BATCH_SIZE
              value: "8"
            - name: USE_GPU
              value: "false"
          ports:
            - containerPort: 8003
          readinessProbe:
            httpGet:
              path: /api/v1/health
              port: 8003
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /api/v1/health
              port: 8003
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: resnet-pytorch
spec:
  type: ClusterIP
  selector:
    app: resnet-pytorch
  ports:
    - protocol: TCP
      port: 8003
      targetPort: 8003
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: resnet-pytorch-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
spec:
  rules:
    - host: resnet-pytorch
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: resnet-pytorch
                port:
                  number: 8003