apiVersion: apps/v1
kind: Deployment
metadata:
  name: resnet-torchscript
spec:
  replicas: 1
  selector:
    matchLabels:
      app: resnet-torchscript
  template:
    metadata:
      labels:
        app: resnet-torchscript
    spec:
      containers:
        - name: resnet-torchscript
          image: svane222/resnet-torchscript:cpu
          env:
            - name: PROMETHEUS_METRICS_ENABLED
              value: "true"
            - name: MAX_BATCH_SIZE
              value: "8"
            - name: USE_GPU
              value: "false"
          ports:
            - containerPort: 8002
          readinessProbe:
            httpGet:
              path: /api/v1/health
              port: 8002
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /api/v1/health
              port: 8002
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: resnet-torchscript
spec:
  type: ClusterIP
  selector:
    app: resnet-torchscript
  ports:
    - protocol: TCP
      port: 8002
      targetPort: 8002
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: resnet-torchscript-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
spec:
  rules:
    - host: resnet-torchscript
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: resnet-torchscript
                port:
                  number: 8002