replicas: 4
console:
  port: 9001
mode: "distributed"
persistence:
  enabled: true
  size: 10Gi
resources:
  requests:
    memory: "512Mi"
    cpu: "500m"
  limits:
    memory: "512Mi"
    cpu: "500m"
existingSecret: minio-secret
extraEnv:
  - name: MINIO_ROOT_USER
    valueFrom:
      secretKeyRef:
        name: minio-secret
        key: MINIO_ROOT_USER
  - name: MINIO_ROOT_PASSWORD
    valueFrom:
      secretKeyRef:
        name: minio-secret
        key: MINIO_ROOT_PASSWORD