from pathlib import Path

BASE_DIRECTORY: Path = Path(__file__).resolve().parent.parent

MODELS_DIRECTORY = BASE_DIRECTORY / "models"
DATA_DIRECTORY = BASE_DIRECTORY / "data"
ADE20K_DIRECTORY = DATA_DIRECTORY / "ADEChallengeData2016"

IMAGE_DIRECTORY = ADE20K_DIRECTORY / "images"
TRAIN_IMAGE_DIRECTORY = IMAGE_DIRECTORY / "training"
VAL_IMAGE_DIRECTORY = IMAGE_DIRECTORY / "validation"

ANNOTATION_DIRECTORY = ADE20K_DIRECTORY / "annotations"
TRAIN_ANNOTATION_DIRECTORY = ANNOTATION_DIRECTORY / "training"
VAL_ANNOTATION_DIRECTORY = ANNOTATION_DIRECTORY / "validation"