apiVersion: apps/v1
kind: Deployment
metadata:
  name: dpt-pytorch
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dpt-pytorch
  template:
    metadata:
      labels:
        app: dpt-pytorch
    spec:
      containers:
        - name: dpt-pytorch
          image: svane222/dpt-pytorch:cpu
          env:
            - name: PROMETHEUS_METRICS_ENABLED
              value: "true"
            - name: MAX_BATCH_SIZE
              value: "8"
            - name: USE_GPU
              value: "false"
          ports:
            - containerPort: 8009
          readinessProbe:
            httpGet:
              path: /api/v1/health
              port: 8009
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /api/v1/health
              port: 8009
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: dpt-pytorch
spec:
  type: ClusterIP
  selector:
    app: dpt-pytorch
  ports:
    - protocol: TCP
      port: 8009
      targetPort: 8009
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dpt-pytorch-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
spec:
  rules:
    - host: dpt-pytorch
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: dpt-pytorch
                port:
                  number: 8009