from pathlib import Path

CURRENT_DIRECTORY = Path(__file__).resolve().parent

OUTPUT_DIRECTORY = CURRENT_DIRECTORY / "output"

DATA_DIRECTORY = CURRENT_DIRECTORY / "data"
DATA_IMAGES_DIRECTORY = DATA_DIRECTORY / "images"
DATA_MASKS_DIRECTORY = DATA_DIRECTORY / "masks"
DATA_BACKGROUNDS_DIRECTORY = DATA_DIRECTORY / "backgrounds"