services:
  swin-onnx:
    image: svane222/swin-onnx:gpu
    environment:
      - PROMETHEUS_METRICS_ENABLED=true
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
      - MAX_BATCH_SIZE=8
      - USE_GPU=true
    gpus: all
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8004/api/v1/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s
    cpus: 1.0
    mem_limit: 4G
    expose:
      - "8004"


  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./configs/nginx/nginx.performance.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      swin-onnx:
        condition: service_healthy


  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./configs/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    restart: always

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus
    restart: always
    volumes:
      - grafana_data:/var/lib/grafana
      - ./configs/grafana/provisioning/:/etc/grafana/provisioning/
      - ./configs/grafana/dashboards/:/var/lib/grafana/dashboards/

volumes:
  prometheus_data:
  grafana_data: