apiVersion: v1
kind: ConfigMap
metadata:
  name: flamenco-worker-config
  namespace: flamenco
data:
  flamenco-worker.yaml: |
    manager_url: http://flamenco-manager:8080/
    task_types: [blender, ffmpeg, file-management, misc]
    restart_exit_code: 47

    # Linux only
    oom_score_adjust: 500
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flamenco-worker
  namespace: flamenco
  labels:
    app: flamenco-worker
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flamenco-worker
  template:
    metadata:
      labels:
        app: flamenco-worker
    spec:
      containers:
        - name: flamenco-worker
          image: svane222/flamenco-worker:latest
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "1Gi"
              cpu: "1000m"
          env:
            - name: FLAMENCO_MANAGER_URL
              value: "http://flamenco-manager:8080"
            - name: FLAMENCO_JOB_STORAGE
              value: "/var/flamenco/output"
          volumeMounts:
            - name: flamenco-output
              mountPath: /var/flamenco/output
            - name: flamenco-config
              mountPath: /opt/flamenco/flamenco-worker.yaml
              subPath: flamenco-worker.yaml
      volumes:
        - name: flamenco-output
          persistentVolumeClaim:
            claimName: flamenco-storage
        - name: flamenco-config
          configMap:
            name: flamenco-worker-config