apiVersion: apps/v1
kind: Deployment
metadata:
  name: flamenco-worker
  namespace: flamenco
  labels:
    app: flamenco-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flamenco-worker
  template:
    metadata:
      labels:
        app: flamenco-worker
    spec:
      containers:
        - name: flamenco-worker
          image: svane222/flamenco-worker:latest
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "1Gi"
              cpu: "1000m"
          volumeMounts:
            - name: flamenco-output
              mountPath: /var/flamenco/output
      volumes:
        - name: flamenco-output
          persistentVolumeClaim:
            claimName: flamenco-storage