apiVersion: v1
kind: ConfigMap
metadata:
  name: flamenco-worker-config
  namespace: flamenco
data:
  config.yaml: |
    manager_url: "http://flamenco-manager.flamenco:8080"
    worker_name: "Kubernetes Worker"
    blender_command: "/usr/bin/blender"
    blender_options: ["--background"]
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flamenco-worker
  namespace: flamenco
  labels:
    app: flamenco-worker
spec:
  replicas: 3 # You can adjust this to scale workers
  selector:
    matchLabels:
      app: flamenco-worker
  template:
    metadata:
      labels:
        app: flamenco-worker
    spec:
      containers:
        - name: flamenco-worker
          image: svane222/flamenco-worker:latest
          resources:
            limits:
              memory: "4Gi"
              cpu: "2000m"
          volumeMounts:
            - name: flamenco-output
              mountPath: /var/flamenco/output
            - name: flamenco-config
              mountPath: /opt/flamenco/config.yaml
              subPath: config.yaml
      volumes:
        - name: flamenco-output
          persistentVolumeClaim:
            claimName: flamenco-storage
        - name: flamenco-config
          configMap:
            name: flamenco-worker-config