apiVersion: v1
kind: ConfigMap
metadata:
  name: flamenco-manager-config
  namespace: flamenco
data:
  flamenco-manager.yaml: |
    _meta:
      version: 3
    manager_name: Flamenco
    database: /var/flamenco/output/flamenco-manager.sqlite
    database_check_period: 10m0s
    listen: :8080
    autodiscoverable: true
    local_manager_storage_path: /var/flamenco/output/flamenco-manager-storage
    shared_storage_path: /var/flamenco/output
    shaman:
      enabled: false
    task_timeout: 10m0s
    worker_timeout: 1m0s
    blocklist_threshold: 3
    task_fail_after_softfail_count: 3
    mqtt:
      client:
        broker: ""
        clientID: flamenco
        topic_prefix: flamenco
        username: ""
        password: ""
    variables:
      blender:
        values:
          - audience: all
            platform: linux
            value: blender
          - audience: all
            platform: windows
            value: blender.exe
          - audience: all
            platform: darwin
            value: blender
      blenderArgs:
        values:
          - audience: all
            platform: all
            value: -b -y
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flamenco-manager
  namespace: flamenco
  labels:
    app: flamenco-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flamenco-manager
  template:
    metadata:
      labels:
        app: flamenco-manager
    spec:
      containers:
        - name: flamenco-manager
          image: svane222/flamenco-manager:latest
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: flamenco-output
              mountPath: /var/flamenco/output
            - name: flamenco-config
              mountPath: /opt/flamenco/flamenco-manager.yaml
              subPath: flamenco-manager.yaml
      volumes:
        - name: flamenco-output
          persistentVolumeClaim:
            claimName: flamenco-storage
        - name: flamenco-config
          configMap:
            name: flamenco-manager-config
---
apiVersion: v1
kind: Service
metadata:
  name: flamenco-manager
  namespace: flamenco
spec:
  selector:
    app: flamenco-manager
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: flamenco-manager-ingress
  namespace: flamenco
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: flamenco-manager.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: flamenco-manager
                port:
                  number: 8080