# Global configuration
scratch:
  resolution: 224

# Dataset configuration
dataset:
  name: "carvana"
  root: "./data"
  batch_size: 32
  pin_memory: true
  train:
    num_workers: 8
    shuffle: true
    drop_last: true
  test:
    num_workers: 8
    shuffle: false
    drop_last: false

# Model configuration
model:
  image_encoder:
    pretrained: true
    freeze_pretrained: true
  mask_decoder:
    out_channels: 1
    dropout: 0.5