# @package _global_

# Global configuration
scratch:
  resolution: 224

# Dataset configuration
dataset:
  name: "carvana"
  root: "./data"
  batch_size: 32
  pin_memory: true
  train:
    num_workers: 8
    shuffle: true
    drop_last: true
  test:
    num_workers: 4
    shuffle: false
    drop_last: false

# Training configuration
training:
  num_epochs: 30
  accelerator: cuda
  seed: 42
  compile_model: true

  # Criterion configuration
  criterion:
    bce_weight: 0.7
    dice_weight: 0.3

  # Optimizer configuration
  optimizer:
    name: "AdamW"
    lr: 1.0e-4
    weight_decay: 1.0e-6
    amp:
      enabled: true
      amp_dtype: float16

  # Scheduler configuration
  scheduler:
    t_max: 10
    eta_min: 1.0e-6

  # Early stopping configuration
  early_stopping:
    enabled: true
    verbose: true
    patience: 5
    min_delta: 0.0
    monitor: "loss"
    mode: "min"

  # Logging configuration
  logging:
    wandb:
      enabled: true
      project: "U-NET"
      entity: "svane20-keyshot"
      tags: [ "unet", "carvana", "segmentation", "experiment" ]
      notes: "Training U-Net on Carvana dataset with mixed precision"
      group: "carvana-segmentation-experiments"
      job_type: "training"
    log: 'all'
    log_freq: 10

  # Checkpoint configuration
  checkpoint:
    save_directory: "./checkpoints"
    checkpoint_path: "unet.pt"
    resume_from: null

# Model configuration
model:
  image_encoder:
    pretrained: true
    freeze_pretrained: false
  mask_decoder:
    out_channels: 1
    dropout: 0.5
