# @package _global_

# Global configuration
scratch:
  resolution: 224

# Dataset configuration
dataset:
  name: "carvana"
  root: "./data"
  batch_size: 16
  pin_memory: true
  train:
    num_workers: 8
    shuffle: true
    drop_last: true
  test:
    num_workers: 4
    shuffle: false
    drop_last: false

# Training configuration
training:
  max_epochs: 100
  warmup_epochs: 10 # 5-10% of max_epochs
  accelerator: cuda
  seed: 42
  compile_model: true

  # Criterion configuration
  criterion:
    name: "MattingLoss"
    weight_dict:
      reconstruction: 1.0
      laplacian: 1.0
      gradient: 0.5
      boundary: 0.5

  # Optimizer configuration
  optimizer:
    name: "AdamW"
    lr: 1.0e-4
    weight_decay: 1.0e-6
    amp:
      enabled: true
      amp_dtype: float16

  # Scheduler configuration
  scheduler:
    name: "CosineAnnealingLR"
    t_max: 90 # 80-90% of max_epochs
    eta_min: 1.0e-5

  # Early stopping configuration
  early_stopping:
    enabled: true
    verbose: true
    patience: 20
    min_delta: 0.0
    monitor: "losses/test_core_loss"
    mode: "min"

  # Logging configuration
  logging:
    wandb:
      enabled: true
      project: "U-NET"
      entity: "svane20-keyshot"
      tags: [ "unet", "carvana", "segmentation", "experiment" ]
      notes: "Training U-Net on Carvana dataset with mixed precision"
      group: "carvana-segmentation-experiments"
      job_type: "training"
    log_directory: "./logs"
    log_freq: 10

  # Checkpoint configuration
  checkpoint:
    save_directory: "./checkpoints"
    checkpoint_path: "unet.pt"
    resume_from: null # "./checkpoints/<CHECKPOINT>" or null

# Model configuration
model:
  image_encoder:
    pretrained: true
    freeze_pretrained: false
  mask_decoder:
    out_channels: 1
    dropout: 0.5
