# Global configuration
scratch:
  resolution: 224

# Model configuration
model:
  name: "UNet"
  image_encoder:
    pretrained: true
    freeze_pretrained: false
  mask_decoder:
    out_channels: 1
    dropout: 0.2

# Deployment configuration
deployment:
  checkpoint_path: "/mnt/shared/ml/checkpoints/unet/unet_v2.pt"
  destination_directory: "/mnt/shared/ml/models/unet"