# Global configuration
scratch:
  resolution: 512

# Dataset configuration
dataset:
  name: "synthetic-data"
  root: "/mnt/shared/datasets/processed"
  batch_size: 16
  pin_memory: true
  train:
    num_workers: 4
    shuffle: true
    drop_last: true
  val:
    num_workers: 4
    shuffle: false
    drop_last: false

# Model configuration
model:
  name: "UNet"
  image_encoder:
    pretrained: true
    freeze_pretrained: true
  mask_decoder:
    out_channels: 1
    dropout: 0.2

# Inference configuration
inference:
  checkpoint_path: "/mnt/shared/ml/checkpoints/unet/unet_v2.pt"