# Global configuration
scratch:
  resolution: 224

# Dataset configuration
dataset:
  name: "synthetic-data"
  root: "D:/OneDrive/Master Thesis/datasets/processed"
  batch_size: 16
  pin_memory: true
  train:
    num_workers: 8
    shuffle: true
    drop_last: true
  test:
    num_workers: 8
    shuffle: false
    drop_last: false

# Model configuration
model:
  name: "UNet"
  image_encoder:
    pretrained: true
    freeze_pretrained: true
  mask_decoder:
    out_channels: 1
    dropout: 0.5