# @package _global_

# Global configuration
scratch:
  resolution: 1024 # Try with 512 next

# Dataset configuration
dataset:
  name: "synthetic-data"
  root: "/mnt/shared/datasets/processed"
  batch_size: 4
  pin_memory: true
  train:
    num_workers: 4
    shuffle: true
    drop_last: true
  val:
    num_workers: 4
    shuffle: false
    drop_last: false

# Training configuration
training:
  max_epochs: 200
  warmup_epochs: 20 # 5-10% of max_epochs
  accelerator: cuda
  seed: 42
  compile_model: true

  # Criterion configuration
  criterion:
    name: "MattingLoss"
    weight_dict:
      reconstruction: 1.0
      laplacian: 0.5
      gradient: 0.5
      boundary: 1.0

  # Optimizer configuration
  optimizer:
    name: "AdamW"
    lr: 3e-4
    weight_decay: 1.0e-7
    amp:
      enabled: true
      amp_dtype: float16
    gradient_clip:
      enabled: true
      max_norm: 0.1
      norm_type: 2

  # Scheduler configuration
  scheduler:
    name: "CosineAnnealingLR"
    enabled: true
    parameters:
      eta_min: 1.0e-7

  # Early stopping configuration
  early_stopping:
    enabled: false
    verbose: true
    patience: 30
    min_delta: 0.0
    monitor: "losses/val_core_loss"
    mode: "min"

  # Logging configuration
  logging:
    wandb:
      enabled: true
      project: "U-NET"
      entity: "svane20-keyshot"
      tags: [ "unet", "synthetic-data", "alpha-matting", "experiment" ]
      notes: "Training U-Net on Synthetic dataset with mixed precision"
      group: "unet-synthetic-experiments"
      job_type: "training"
    log_directory: "./logs"
    log_metrics: false
    log_freq: 10

  # Checkpoint configuration
  checkpoint:
    save_directory: "/mnt/shared/ml/checkpoints/unet"
    save_freq: 5
    checkpoint_path: "unet_v5.pt"
    resume_from: null # "./checkpoints/<CHECKPOINT>" or null

# Model configuration
model:
  name: "UNet"
  image_encoder:
    pretrained: true
    freeze_pretrained: false
  mask_decoder:
    out_channels: 1
    dropout: 0.2
