# Global configuration
scratch:
  resolution: 512

# Model configuration
model:
  encoder:
    pretrained: true
  decoder:
    encoder_channels: [64, 64, 128, 256, 512]
    decoder_channels: [256, 128, 64, 64]
    final_channels: 64

# Deployment configuration
deployment:
  checkpoint_path: "/mnt/shared/ml/checkpoints/unet/unet_v1.pt"
  destination_directory: "/mnt/shared/ml/models/unet"