# Global configuration
scratch:
  resolution: 512

# Model configuration
model:
  name: "UNet"
  image_encoder:
    pretrained: true
    freeze_pretrained: true
  mask_decoder:
    out_channels: 1
    dropout: 0.2

# Deployment configuration
deployment:
  checkpoint_path: "D:/OneDrive/Master Thesis/ml/checkpoints/unet/unet_v2.pt"
  destination_directory: "D:/OneDrive/Master Thesis/ml/models/unet"