# Global configuration
scratch:
  resolution: 512

# Model configuration
model:
  image_encoder:
    pretrained: true
    freeze_pretrained: false

# Deployment configuration
deployment:
  checkpoint_path: "D:/OneDrive/Master Thesis/ml/checkpoints/unet/unet_v1.pt"
  destination_directory: "D:/OneDrive/Master Thesis/ml/models/unet"
  compile_model: false