# Global configuration
scratch:
  resolution: 512

# Model configuration
model:
  encoder:
    pretrained: true
    freeze_pretrained: true

# Deployment configuration
deployment:
  checkpoint_path: "/mnt/shared/ml/checkpoints/unet/unet_v1.pt"
  destination_directory: "/mnt/shared/ml/models/unet"