# Global configuration
scratch:
  resolution: 224
  crop_resolution: null

# Dataset configuration
dataset:
  name: "synthetic-data"
  root: "/mnt/shared/datasets/processed"
  batch_size: 1
  pin_memory: true
  test:
    num_workers: 4
    shuffle: false
    drop_last: false

# Evaluation configuration
evaluation:
  checkpoint_path: "/mnt/shared/ml/checkpoints/unet/resnet_50_224_v2.pt"
  compile_model: true

  # Inference configuration
  inference:
    use_sliding_window: true
    tile_size: 224
    overlap: 32

# Model configuration

# ResNet-34
#model:
#  model_name: "ResNet34Matte"
#  encoder:
#    pretrained: true
#  decoder:
#    encoder_channels: [ 64, 64, 128, 256, 512 ]
#    decoder_channels: [ 256, 128, 64, 64 ]
#    final_channels: 64

# ResNet-50
model:
  model_name: "ResNet50Matte"
  encoder:
    pretrained: true
  decoder:
    encoder_channels: [ 64, 256, 512, 1024, 2048 ]
    decoder_channels: [ 512, 256, 128, 64 ]
    final_channels: 64