# Global configuration
scratch:
  resolution: 512

# Dataset configuration
dataset:
  name: "synthetic-data"
  root: "D:/OneDrive/Master Thesis/datasets/processed"
  batch_size: 16
  pin_memory: true
  test:
    num_workers: 4
    shuffle: false
    drop_last: false

# Model configuration
model:
  encoder:
    pretrained: true
  decoder:
    encoder_channels: [64, 64, 128, 256, 512]
    decoder_channels: [256, 128, 64, 64]
    final_channels: 64

# Inference configuration
evaluation:
  checkpoint_path: "D:/OneDrive/Master Thesis/ml/checkpoints/unet/unet_v1.pt"
  compile_model: false