# Global configuration
scratch:
  resolution: 512

# Dataset configuration
dataset:
  name: "synthetic-data"
  root: "/mnt/shared/datasets/processed"
  batch_size: 16
  pin_memory: true
  test:
    num_workers: 4
    shuffle: false
    drop_last: false

# Model configuration
model:
  encoder:
    pretrained: true
    freeze_pretrained: true

# Inference configuration
evaluation:
  checkpoint_path: "/mnt/shared/ml/checkpoints/unet/unet_v1.pt"
  compile_model: true