# @package _global_

# Global configuration
scratch:
  resolution: 512

# Dataset configuration
dataset:
  name: "synthetic-data"
  root: "/mnt/shared/datasets/processed"
  batch_size: 16
  pin_memory: true
  train:
    num_workers: 4
    shuffle: true
    drop_last: true
  val:
    num_workers: 4
    shuffle: false
    drop_last: false

# Training configuration
training:
  max_epochs: 100
  warmup_epochs: 10 # 5-10% of max_epochs
  accelerator: cuda
  seed: 42
  compile_model: true

  # Criterion configuration
  criterion:
    name: "MattingLoss"
    weight_dict:
      composition: 1.0 # 1.0
      gradient: 1.0 # 0.25
      l1: 1.0 # 0.8
      laplacian: 1.5 # 0.5

  # Optimizer configuration
  optimizer:
    name: "AdamW"
    lr: 4e-4
    weight_decay: 1.0e-7
    amp:
      enabled: true
      amp_dtype: float16
    gradient_clip:
      enabled: true
      max_norm: 0.1
      norm_type: 2

  # Scheduler configuration
  scheduler:
    name: "CosineAnnealingLR"
    enabled: true
    parameters:
      eta_min: 1.0e-7

  # Early stopping configuration
  early_stopping:
    enabled: true
    verbose: true
    patience: 30
    min_delta: 0.0
    monitor: "mae"
    mode: "min"

  # Logging configuration
  logging:
    wandb:
      enabled: true
      project: "U-NET"
      entity: "svane20-keyshot"
      tags: [ "unet", "resnet-34", "synthetic-data" ]
      notes: "Training U-Net with ResNet-34 backbone on synthetic data."
      group: "unet"
      job_type: "training"
    log_directory: "./logs"
    log_metrics: false
    log_freq: 10

  # Checkpoint configuration
  checkpoint:
    save_directory: "/mnt/shared/ml/checkpoints/unet"
    save_freq: 5
    checkpoint_path: "unet_v2.pt"
    resume_from: null # "/mnt/shared/ml/checkpoints/unet/<CHECKPOINT>" or null

# Model configuration
model:
  encoder:
    pretrained: true
  decoder:
    encoder_channels: [64, 64, 128, 256, 512]
    decoder_channels: [256, 128, 64, 64]
    final_channels: 64