apiVersion: apps/v1
kind: Deployment
metadata:
  name: swin-torchscript
spec:
  replicas: 1
  selector:
    matchLabels:
      app: swin-torchscript
  template:
    metadata:
      labels:
        app: swin-torchscript
    spec:
      containers:
        - name: swin-torchscript
          image: svane222/swin-torchscript:cpu
          env:
            - name: PROMETHEUS_METRICS_ENABLED
              value: "true"
            - name: MAX_BATCH_SIZE
              value: "8"
            - name: USE_GPU
              value: "false"
          ports:
            - containerPort: 8005
---
apiVersion: v1
kind: Service
metadata:
  name: swin-torchscript
spec:
  type: ClusterIP
  selector:
    app: swin-torchscript
  ports:
    - protocol: TCP
      port: 8005
      targetPort: 8005
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: swin-torchscript-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
spec:
  rules:
    - host: swin-torchscript
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: swin-torchscript
                port:
                  number: 8005