# @package _global_

# Deployment configuration
deployment:
  resolution: 512
  hardware_acceleration: "cuda"  # Options: "cpu", "cuda"
  checkpoint_path: "D:/OneDrive/Master Thesis/ml/checkpoints/dpt/dpt-swinv2-tiny-256_v1.pt"
  destination_directory: "D:/OneDrive/Master Thesis/ml/models/dpt"
  optimizations:
    apply_quantization: true
    apply_pruning: true

# Model configuration
model:
  model_name: "DPTSwinV2Tiny256Matte"
  encoder:
    model_name: "Intel/dpt-swinv2-tiny-256"
  decoder:
    in_channels: 768
    convstream_out: [ 48, 96, 192, 384, 512 ]
    fusion_out: [ 48, 96, 192, 384, 512 ]