# @package _global_

# Data augmentation configuration
transforms:
  test:
    Resize:
      size: [ 512, 512 ]
    ToTensor: { }
    Rescale:
      scale: 0.00392156862745098 # 1/255
    Normalize:
      mean: [ 0.5, 0.5, 0.5 ]
      std: [ 0.5, 0.5, 0.5 ]
      inplace: false

# Dataset configuration
dataset:
  name: "synthetic-data"
  root: "/mnt/shared/datasets/processed"
  batch_size: 4
  pin_memory: true
  test:
    num_workers: 4
    shuffle: false
    drop_last: false

# Evaluation configuration
evaluation:
  checkpoint_path: "/mnt/shared/ml/checkpoints/dpt/dpt-swinv2-tiny-512_v2.pt"
  compile_model: true

# Model configuration
model:
  model_name: "DPTSwinV2Tiny256Matte"
  encoder:
    model_name: "Intel/dpt-swinv2-tiny-256"
  decoder:
    in_channels: 768
    convstream_out: [ 48, 96, 192, 384, 512 ]
    fusion_out: [ 48, 96, 192, 384, 512 ]