# @package _global_

# Deployment configuration
deployment:
  resolution: 512
  hardware_acceleration: "cuda"  # Options: "cpu", "cuda"
  checkpoint_path: "/mnt/shared/ml/checkpoints/swin/swin_small_patch4_window7_224_512_v1_latest.pt"
  destination_directory: "/mnt/shared/ml/models/swin"
  optimizations:
    apply_quantization: true
    apply_pruning: true

# Model configuration
model:
  model_name: "SwinMattingModel"
  encoder:
    model_name: "microsoft/swin-small-patch4-window7-224"
  decoder:
    use_attn: true
    refine_channels: 16