# @package _global_

# Data augmentation configuration
transforms:
  test:
    Resize:
      size: [ 512, 512 ]
    ToTensor: { }
    Rescale:
      scale: 0.00392156862745098 # 1/255
    Normalize:
      mean: [ 0.485, 0.456, 0.406 ]
      std: [ 0.229, 0.224, 0.225 ]
      inplace: false

# Dataset configuration
dataset:
  name: "synthetic-data"
  root: "/mnt/shared/datasets/processed"
  batch_size: 2
  pin_memory: true
  test:
    num_workers: 4
    shuffle: false
    drop_last: false

# Evaluation configuration
evaluation:
  checkpoint_path: "/mnt/shared/ml/checkpoints/swin/swin_small_patch4_window7_224_512_v1.pt"
  compile_model: true

# Model configuration
model:
  model_name: "SwinMattingModel"
  encoder:
    model_name: "microsoft/swin-small-patch4-window7-224"
  decoder:
    use_attn: true
    refine_channels: 16