# @package _global_

scratch:
  resolution: 224
  batch_size: 16
  num_workers: 4
  num_epochs: 100

# Training configuration
training:
  mode: train
  accelerator: cuda
  seed: 42

# Model configuration
model:
  image_encoder:
    pretrained: true
  mask_decoder:
    out_channels: 1
    dropout: 0.5

# Optimizer configuration
optimizer:
  learning_rate: 1.0e-4
  amp:
    enabled: true
    amp_dtype: float16
