# @package _global_

# Training configuration
scratch:
  resolution: 224
  batch_size: 16
  num_workers: 4
  learning_rate: 1.0e-4
  num_epochs: 100

# Model configuration
model:
  image_encoder:
    pretrained: true
  mask_decoder:
    out_channels: 1
    dropout: 0.5