# Global configuration
scratch:
  resolution: 512

# Dataset configuration
dataset:
  name: "synthetic-data"
  root: "D:/OneDrive/Master Thesis/datasets/processed"
  batch_size: 16
  pin_memory: true
  train:
    num_workers: 4
    shuffle: true
    drop_last: true
  test:
    num_workers: 4
    shuffle: false
    drop_last: false

# Model configuration
model:
  image_encoder:
    pretrained: true
    freeze_pretrained: false

# Inference configuration
inference:
  checkpoint_path: "D:/OneDrive/Master Thesis/ml/checkpoints/unet/unet_resnet_34_v2.pt"