# @package _global_

# Deployment configuration
deployment:
  resolution: 512
  hardware_acceleration: "cuda"  # Options: "cpu", "cuda"
  checkpoint_path: "/mnt/shared/ml/checkpoints/resnet/resnet_50_512_v1.pt"
  destination_directory: "/mnt/shared/ml/models/resnet"
  optimizations:
    apply_pruning: true

# Model configuration

# ResNet-34
#model:
#  model_name: "ResNet34Matte"
#  encoder:
#    pretrained: true
#  decoder:
#    encoder_channels: [ 64, 64, 128, 256, 512 ]
#    decoder_channels: [ 256, 128, 64, 64 ]
#    final_channels: 64

# ResNet-50
model:
  model_name: "ResNet50Matte"
  encoder:
    pretrained: true
  decoder:
    encoder_channels: [ 64, 256, 512, 1024, 2048 ]
    decoder_channels: [ 512, 256, 128, 64 ]
    final_channels: 64