# @package _global_

# Data augmentation configuration
transforms:
  test:
    Resize:
      size: [ 512, 512 ]
    ToTensor: { }
    Rescale:
      scale: 0.00392156862745098 # 1/255
    Normalize:
      mean: [ 0.485, 0.456, 0.406 ]
      std: [ 0.229, 0.224, 0.225 ]
      inplace: false

# Dataset configuration
dataset:
  name: "synthetic-data"
  root: "C:/Users/svane/Desktop/Thesis/datasets"
  batch_size: 8
  pin_memory: true
  test:
    num_workers: 4
    shuffle: false
    drop_last: false

# Evaluation configuration
evaluation:
  checkpoint_path: "D:/OneDrive/Master Thesis/ml/checkpoints/unet/resnet_50_512_v1.pt"
  compile_model: false

# Model configuration

# ResNet-34
#model:
#  model_name: "ResNet34Matte"
#  encoder:
#    pretrained: true
#  decoder:
#    encoder_channels: [ 64, 64, 128, 256, 512 ]
#    decoder_channels: [ 256, 128, 64, 64 ]
#    final_channels: 64

# ResNet-50
model:
  model_name: "ResNet50Matte"
  encoder:
    pretrained: true
  decoder:
    encoder_channels: [ 64, 256, 512, 1024, 2048 ]
    decoder_channels: [ 512, 256, 128, 64 ]
    final_channels: 64