name: Build and Push Docker Image

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

#      - name: Set up Docker Buildx
#        uses: docker/setup-buildx-action@v3
#
#      - name: Build Docker image
#        run: |
#          docker build -t flamenco-api ./web-services/flamenco-api
#
#      - name: Log in to Docker Hub
#        uses: docker/login-action@v3
#        with:
#          username: ${{ secrets.DOCKER_HUB_USERNAME }}
#          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
#
#      - name: Push Docker image
#        run: |
#          docker tag blender-web-api:latest ${{ secrets.DOCKER_HUB_USERNAME }}/flamenco-api:latest
#          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/flamenco-api:latest
